spring.data.mongodb.uri=mongodb+srv://chetanyabansal410_db_user:LR53jdeNsE4nuX1h@cluster0.p9ejmqn.mongodb.net/taskmanager?appName=Cluster0
spring.application.name=task-manager
spring.main.allow-bean-definition-overriding=true